# Generated by Django 4.0.5 on 2022-06-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='College_clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('books', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LibMng.books')),
                ('clubs', models.ManyToManyField(to='LibMng.college_clubs')),
                ('course', models.ManyToManyField(to='LibMng.courses')),
                ('dept_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LibMng.department')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('emp_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=128)),
                ('salary', models.CharField(max_length=28)),
                ('course', models.ManyToManyField(to='LibMng.courses')),
                ('dept_name', models.ManyToManyField(to='LibMng.department')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='dept_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LibMng.department'),
        ),
        migrations.CreateModel(
            name='Books_borrowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowedbooks', to='LibMng.books')),
                ('st_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LibMng.student')),
            ],
        ),
    ]
