# Generated by Django 4.0.5 on 2022-06-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibMng', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='books',
        ),
    ]
